version: '3.3'

networks:
  auth-network:
    driver: bridge

volumes:
  auth-mysql-volume:

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    networks:
      - auth-network
    volumes:
      - auth-mysql-volume:/var/lib/mysql
